import Image from 'next/image'
import {getContentFulArticles, getContentFulArticle, getContentFulNavbar} from '../../lib/api'
import Head from 'next/head'
import Layout from '@/components/Layout'

export const getStaticPaths = async () => {

    const articles = await getContentFulArticles()

    const paths = articles.items.map(article => {
        console.log("one article: ", article.sys.id)
        return {
            params: {
                articleId: article.sys.id
            }
        }
    })

    console.log("paths: ", paths)

    return {
        paths,
        fallback: false
    }

}

export const getStaticProps = async ({params}) => {

    console.log("params.slug: ", params.articleId)

    const article = await getContentFulArticle(params.articleId)

    return {
        props: {
            article,
            navbar: await getContentFulNavbar()
        }
    }

}

const article = ({article, navbar}) => {
    return (
        <>
            <Head>
                <title>{`${article.fields.title} | Create Next App`}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout navbar={navbar}>
                <div className='p-4 w-1/2'>
                    <h1 className='text-3xl font-bold mb-4'>{article.fields.title}</h1>
                    <Image 
                        src={'https:' + article.fields.image.fields.file.url}
                        width={article.fields.image.fields.file.details.image.width}
                        height={article.fields.image.fields.file.details.image.height}
                        alt={`${article.fields.title} image`}
                        priority
                        className='h-96'
                    />
                    <h2 className='text-lg font-bold mt-1.5 mb-3'>{article.fields.subheading}</h2>
                    <p>{article.fields.text}</p>
                </div>
            </Layout>
        </>
        
    )
}

export default article