import Head from 'next/head'
import Layout from '@/components/Layout'
import Articles from '@/components/Articles'
import {getContentFulNavbar, getContentFulArticles} from '../../lib/api'

export const getStaticProps = async () => {

    return {
        props: {
            elements: {
                navbar: await getContentFulNavbar(),
                articles: await getContentFulArticles()
              }
        }
    }

}

const articles = ({elements}) => {

    console.log(elements.articles)

    return (
    <>
      <Head>
        <title>Articles | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout navbar={elements.navbar}>
        <h2>Our articles</h2>
        {
          elements.articles.total && <Articles articles={elements.articles} />
        }
      </Layout>
      
    </>
    )

}

export default articles