import { createClient } from "contentful"
import { createElement } from "react"
import Card from "@/components/Card"
import Test from "@/components/Test"
import Hero from "@/components/Hero"
import Articles from "@/components/Articles"
import Layout from "@/components/Layout"
import { getContentFulNavbar } from '@/lib/api'
import Head from "next/head"

const components = {
    test: Test,
    card: Card,
    hero: Hero,
    article: Articles
}

const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN
  })

export const getServerSideProps = async (context) => {

    console.log('context.params: ', context.params)
    const {slug} = context.params

    console.log('the slug is: ', slug)

    const pages = await client.getEntries({
        content_type: 'page',
        'fields.slug': slug
    })

    const navbar = await getContentFulNavbar()

    console.log('navbar in slug, ', navbar)

    return {
        props: {
            pages,
            navbar
        }
    }
}

const getComponent = (item) => {

    console.log('hellooooooo', item)

    return createElement(components[item.sys.contentType.sys.id], {
        item,
        key: item.sys.id
    })

}

const Page = (props) => {

    if (!props.pages.total) {
        return (
            <div>page not found</div>
        )
    }

    console.log("pages items: ", props.pages.items[0].fields.sections)
    const section = props.pages.items[0].fields.sections[0]
    console.log("type of item: ", section.sys.contentType.sys.id)

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout navbar={props.navbar}>
                { props.pages.items[0].fields.sections.map(item => getComponent(item)) }
            </Layout>
        </>
    )

}

export default Page